
export const GET_BOOKING_REQUEST = 'GET_BOOKING_REQUEST';
export const GET_BOOKING_SUCCESS = 'GET_BOOKING_SUCCESS';
export const GET_BOOKING_FAIL = 'GET_BOOKING_FAIL';

export const BOOKING_UPDATE_REQUEST = 'BOOKING_UPDATE_REQUEST';
export const BOOKING_UPDATE_SUCCESS = 'BOOKING_UPDATE_SUCCESS';
export const BOOKING_UPDATE_FAIL = 'BOOKING_UPDATE_FAIL';

export const GET_PAYMENT_REQUEST = 'GET_PAYMENT_REQUEST';
export const GET_PAYMENT_SUCCESS = 'GET_PAYMENT_SUCCESS';
export const GET_PAYMENT_FAIL = 'GET_PAYMENT_FAIL';



