export const GET_REPORT_REQUEST = 'GET_REPORT_REQUEST';
export const GET_REPORT_SUCCESS = 'GET_REPORT_SUCCESS';
export const GET_REPORT_FAIL = 'GET_REPORT_FAIL';

export const REPORT_UPDATE_REQUEST = 'REPORT_UPDATE_REQUEST';
export const REPORT_UPDATE_SUCCESS = 'REPORT_UPDATE_SUCCESS';
export const REPORT_UPDATE_FAIL = 'REPORT_UPDATE_FAIL';


export const GET_FEEDBACK_REQUEST = 'ADD_FEEDBACK_REQUEST';
export const GET_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const GET_FEEDBACK_FAIL = 'ADD_FEEDBACK_FAIL'


export const ADD_FEEDBACK_REQUEST = 'ADD_FEEDBACK_REQUEST';
export const ADD_FEEDBACK_SUCCESS = 'ADD_FEEDBACK_SUCCESS';
export const ADD_FEEDBACK_FAIL = 'ADD_FEEDBACK_FAIL'

