export const GET_TIMESLOT_REQUEST = 'GET_TIMESLOT_REQUEST';
export const GET_TIMESLOT_SUCCESS = 'GET_TIMESLOT_SUCCESS';
export const GET_TIMESLOT_FAIL = 'GET_TIMESLOT_FAIL';

export const TIMESLOT_UPDATE_REQUEST = 'TIMESLOT_UPDATE_REQUEST';
export const TIMESLOT_UPDATE_SUCCESS = 'TIMESLOT_UPDATE_SUCCESS';
export const TIMESLOT_UPDATE_FAIL = 'TIMESLOT_UPDATE_FAIL';

