export const USER_SIGNIN_REQUEST = 'USER_SIGNIN_REQUEST';
export const USER_SIGNIN_SUCCESS = 'USER_SIGNIN_SUCCESS';
export const USER_SIGNIN_FAIL = 'USER_SIGNIN_FAIL';

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST';
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS';
export const USER_UPDATE_FAIL = 'USER_UPDATE_FAIL';

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST';
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS';
export const USER_REGISTER_FAIL = 'USER_REGISTER_FAIL';

export const GET_USERLIST_REQUEST = 'GET_USERLIST_REQUEST';
export const GET_USERLIST_SUCCESS = 'GET_USERLIST_SUCCESS';
export const GET_USERLIST_FAIL = 'GET_USERLIST_FAIL';

export const DELETE_USER_REQUEST = 'DELETE_USER_REQUEST';
export const DELETE_USER_SUCCESS = 'DELETE_USER_SUCCESS';
export const DELETE_USER_FAIL = 'DELETE_USER_FAIL';

export const GET_USERDATA_REQUEST = 'GET_USERDATA_REQUEST';
export const GET_USERDATA_SUCCESS = 'GET_USERDATA_SUCCESS';
export const GET_USERDATA_FAIL = 'GET_USERDATA_FAIL';

export const GET_CHILDLIST_REQUEST = 'GET_CHILDLIST_REQUEST';
export const GET_CHILDLIST_SUCCESS = 'GET_CHILDLIST_SUCCESS';
export const GET_CHILDLIST_FAIL = 'GET_CHILDLIST_FAIL';

export const GET_TUTORLIST_REQUEST = 'GET_TUTORLIST_REQUEST';
export const GET_TUTORLIST_SUCCESS = 'GET_TUTORLIST_SUCCESS';
export const GET_TUTORLIST_FAIL = 'GET_TUTORLIST_FAIL';

export const GET_SELFDATA_REQUEST = 'GET_SELFDATA_REQUEST';
export const GET_SELFDATA_SUCCESS = 'GET_SELFDATA_SUCCESS';
export const GET_SELFDATA_FAIL = 'GET_SELFDATA_FAIL';

export const USER_LOGOUT = 'USER_LOGOUT';